import os
import contextlib


@contextlib.contextmanager
def suppress_print():
    """
    Used to supress non-togglable print statements generated by yfinance
    :return:
    """
    with open(os.devnull, "w") as f, contextlib.redirect_stdout(f):
        yield
