@startuml object_model
package facades {
    interface TradingAPI {
        + buy(symbol, quantity, price)
        + sell(symbol, count, price)
        + balance() float
        + shares(symbol) int
    }

    interface HistoricalNewsDataAPI {
        + historical_news(symbol, start, duration) List[News]
    }

    interface HistoricalMarketDataAPI {
        + was_market_open(date) bool
        + historical_bars(symbol start, duration, buckets) List[Bar]
        + historical_trades(symbol, start, duration) List[Trade]
        + historical_quotes(symbol, start, duration) List[Quote]
    }

    interface NewsDataAPI {
        + news(symbol) List[News]
    }

    HistoricalNewsDataAPI <-- NewsDataAPI

    interface MarketDataAPI {
        + is_market_open() bool
        + bars(symbol, buckets) List[Bar]
        + trades(symbol) List[Trade]
        + quotes(symbol) Quote
    }

    HistoricalMarketDataAPI <-- MarketDataAPI

    interface SymbolDataAPI {
        + get_ticker_symbols(timestamp) List[str]
        + get_float(symbol) int
        + get_floats(symbols) Dict[str, int]
        + get_ticker(symbol) TickerMeta
        + historical_ticker(symbol, start, duration) List[TickerMeta]
    }

    class UnififedAPI {
        + trader
        + market
        + symbols
        + news_api
    }

    TradingAPI <-- UnififedAPI
    MarketDataAPI <-- UnififedAPI
    SymbolDataAPI <-- UnififedAPI
    NewsDataAPI <-- UnififedAPI
}
package models {
    class SymbolData {
        + symbol
    }

    class HistoricalData {
        + timestamp
    }

    SymbolData --|> HistoricalData

    class Bar {
        + open
        + close
        + high
        + low
        + volume

        + zero() bool
        + tradeless() bool
    }

    HistoricalData --|> Bar

    class Trade {
        + exchange
        + count
        + price
    }

    HistoricalData --|> Trade

    class Quote {
        + ask_exchange
        + ask_size
        + ask_price
        + bid_exchange
        + bid_size
        + bid_price
    }

    SymbolData --|> Quote

    class HistoricalQuote {
        + ask_exchange
        + ask_size
        + ask_price
        + bid_exchange
        + bid_size
        + bid_price
    }

    HistoricalData --|> HistoricalQuote

    class News {
        + news_id
        + author
        + headline
        + url
        + updated_at
    }

    HistoricalData --|> News

    class TickerMeta {
        + symbol
        + date
        + float
        + current_price
        + open
        + change_since_open
    }
}

package utils {
    package structures {
        package caching {
            interface ReadOnlyCacheAPI {
                + select(name, columns, condition, extras, params) List[tuple]
                + exists(name, columns, condition, params) bool
                + custom_query(query, params) List[tuple]
            }

            interface CacheAPI {
                + reset_connection()
                + create_table(name, definition)
                + delete_table(name)
                + insert_row(name, parameters, columns, collision_resolution)
                + insert_rows(name, parameters, columns, collision_resolution)
                + custom_query(query, params)
                + custom_nr_query(query, params, commit)
            }

            ReadOnlyCacheAPI <-- CacheAPI

            abstract class CachedClass {
                + db: CacheAPI

                + setup_tables()
                + cache_check(name, columns, condition, params) bool
                + cache_lookup(name, columns, condition, extras, params) List[tuple]
                + cache_save(name, params, columns, force)
                + cache_save_many(name, params, columns, force)
            }

            class ReadOnlyCachedClass {
                + db: ReadOnlyCacheAPI

                + cache_check(name, columns, condition, params) bool
                + cache_lookup(name, columns, condition, extras, params) List[tuple]
            }
        }
    }
}

package trading {
    package alpaca {
        class AlpacaTrader {
            + api_key
            + api_secret
            + paper
            - mdclient
            - tclient
            - nclient
            + last_req

            - connect()
            - handle_request()
            - check_exists(tbl_pre, symbol, date) bool
            - save_exists(tbl_pre, symbol, date)
            + cancel_all()
            + get_current_price(symbol) float
            + position(symbol) Position
        }

        CachedClass --|> AlpacaTrader
        MarketDataAPI <-- AlpacaTrader
        TradingAPI <-- AlpacaTrader
        NewsDataAPI <-- AlpacaTrader

        class AlpacaTraderManualBars

        AlpacaTrader --|> AlpacaTraderManualBars
    }
}

package market {
    package polyhoo {
        class PolyHooSymbolData {
            + polygon_key

            + is_delisted(symbol, d) bool
        }

        CachedClass --|> PolyHooSymbolData
        SymbolDataAPI <-- PolyHooSymbolData

        class StaticFilteredPolyHooSymbolData {
            + filters
        }

        PolyHooSymbolData --|> StaticFilteredPolyHooSymbolData
    }
}

package apis {
    package alpolyhoo {
        class AlPolyHooAPI
        UnififedAPI --|> AlPolyHooAPI

        class AlPolyHooStaticFilterAPI
        UnififedAPI --|> AlPolyHooStaticFilterAPI

        class AlFinnPolyHooStaticFilterAPI
        UnififedAPI --|> AlFinnPolyHooStaticFilterAPI
    }

    package sql {
        class SqliteController {
            + loc
            - conn
            + can_commit

            + connect()
            + commit()
            + close()
            - start_query(query, params) Cursor
            - finish_query(commit, cur)
            + nr_query(query, params, commit)
            + query(query, params, commit) list
            + nr_query_many(query, params, commit)
        }

        class ReadOnlySqliteController {
            + loc

            + query(query, params) list
        }

        class SqliteAPI {
            - conn

            + commit()
            + disable_commiting()
            + enable_commiting()
        }

        CacheAPI <-- SqliteAPI

        class ReadOnlySqliteAPI {
            - conn
        }

        ReadOnlyCacheAPI <-- ReadOnlySqliteAPI
    }
}
@enduml